import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import styled from 'styled-components';
import { theme } from '@/styles/theme';
import { Button } from '@/components/Button/Button';
import Link from 'next/link';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const router = useRouter();

  const handleClick = () => {
    console.log(`Placing your order `);
    // setTimeout(() => {
    //   router.push(`/product`);
    // }, 3000);
    router.push(`/product`);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <h1>Hello</h1>
        <h2>Blue</h2>
        <p style={{ color: theme.colors.danger }}>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Est
          voluptate explicabo doloremque?
        </p> */}
        {/* <div style={{ padding: '12px', display: 'flex', gap: '5px' }}>
          <Button>Normal</Button>
          <Button
            color={'white'}
            background={'red'}
            hoverBg={'green'}
            hoverColor={'red'}
            rounded
            size={'large'}
          >
            Normal
          </Button>
          <Button
            color={'white'}
            background={'green'}
            hoverBg={'blue'}
            hoverColor={'red'}
            size={'medium'}
            edged
          >
            Normal
          </Button>
          <Button
            color={'white'}
            background={'blue'}
            hoverBg={'yellow'}
            hoverColor={'red'}
            size={'small'}
            fineRadius
          >
            Normal
          </Button> */}
        {/* </div> */}
        Hello
        <Link href={'/blog'}> Blog </Link>
        <Link href={'/product'}> Product </Link>
        <button onClick={handleClick}>Place Order</button>
      </main>
    </>
  );
}
